apiVersion: v1
kind: Service
metadata:
  name: antiracism-backend-service
spec:
  type: NodePort
  selector:
    app: antiracism
  ports:
    - protocol: TCP
      nodePort: 30003
      port: 8081
      targetPort: 4000
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: antiracism-backend-deployment 
  labels: 
    app: antiracism 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: antiracism 
  template: 
    metadata: 
      labels: 
        app: antiracism 
    spec: 
      containers: 
      - name: antiracism-container 
        image: tvaskisalo/sof_con_2022:sof_con_backend 
        ports: 
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: antiracism-frontend-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30002
      port: 8091
      targetPort: 80
  selector:
    app: sof_con_frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: antiracism-frontend-deployment
  labels:
    app: sof_con_frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sof_con_frontend
  template:
    metadata:
      labels:
        app: sof_con_frontend
    spec:
      containers:
      - name: antiracism-frontend-container
        image: tvaskisalo/sof_con_2022:sof_con_frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: z-volume
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/data"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: antiracism-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.helm/v1
kind: Ingress
metadata:
  name: antiracism-gke-ingress
spec:
  ingressClassName: nginx-antiracism
  rules:
  - http:
      paths:
      - path: /external-api-antiracism
        pathType: ImplementationSpecific
        backend:
          service:
            name: test
            port:
              number: 8090

