apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: antiracism-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 1Gi