apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: incoming-http-traffic
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: antiracismapp-frontend-7dbbd48585-rdtzn
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 80
